language: python
python:
  - "3.6"
  - "3.7-dev"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c "CREATE DATABASE testauthor;" -U postgres
  - psql -c "ALTER user postgres PASSWORD 'pass';" -U postgres
  - export DATABASE_URL="postgresql://postgres:pass@localhost/testauthor"
  - export SENDGRID_KEY="sengridkey"
  - export HOST_USER="username"
  - export HOST_PASSWORD="password"
  - python manage.py makemigrations
  - python manage.py migrate
  - export SENDGRID_API_KEY='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'
services:
  - postgresql

script:
  - coverage run --source=authors manage.py test # will run the tests and give back coverage analysis in the .coverage file
  - coverage report
  - coveralls

after-success:
  - coveralls
