language: python
python:
  - "3.6"
  - "3.7-dev" 

# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - python manage.py makemigrations
  - python manage.py migrate

services:
#  - postgresql

script:
  - python manage.py test