# Generated by Django 2.1.4 on 2019-04-04 09:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 4, 9, 11, 26, 776143, tzinfo=utc)),
        ),
    ]
