# Generated by Django 2.1 on 2019-04-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='article_slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
