# Generated by Django 2.1.4 on 2019-04-17 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190416_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportarticle',
            name='article',
        ),
        migrations.RemoveField(
            model_name='reportarticle',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReportArticle',
        ),
    ]
