# Generated by Django 2.1 on 2019-04-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190404_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='article_slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='comments',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
