# Generated by Django 2.1.4 on 2019-04-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190417_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='flagged',
            field=models.CharField(default='', max_length=150),
        ),
    ]
