# Generated by Django 2.1.4 on 2019-04-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_articles_flagged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='flagged',
            new_name='flag',
        ),
    ]
