# Generated by Django 2.1.4 on 2019-04-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20190418_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportarticle',
            name='action_taken',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
