# Generated by Django 2.1.4 on 2019-04-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20190418_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportarticle',
            name='flag',
        ),
        migrations.AlterField(
            model_name='reportarticle',
            name='action_taken',
            field=models.CharField(default='Pending', max_length=200),
        ),
    ]
